name: AutoBuildWebGL 😎

on:
  workflow_dispatch:
  push:
    tags:
      - Build_*

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.1.1
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.4.7f1
          targetPlatform: WebGL
          buildName: .

      # Copy to destination
      - name: Copy to destination
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /build/WebGL
          dst_path: /docs
          dst_owner: tianlang0704
          dst_repo_name: Choice

      # # Add change
      # - name: Commit output
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add docs
      #     git commit -m "AutoBuildWebGL"

      # # Push
      # - name: GitHub Push
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: $\{{ secrets.GITHUB_TOKEN }}
