name: AutoBuildWebGL 😎

on:
  workflow_dispatch:
  push:
    tags:
      - Build_*

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.1.1
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.4.7f1
          targetPlatform: WebGL
          buildsPath: docs
          buildName: .

      # copy fild to correct release path
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "docs/WebGL"
          target: "docs"

      # remove old folder
      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: docs/WebGL

      # Add change
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "AutoBuildWebGL"

      # Push
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: $\{{ secrets.GITHUB_TOKEN }}
